// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestLab.DataAccess;

#nullable disable

namespace TestLab.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20251218173921_FixedSeedData")]
    partial class FixedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AdditionalServicesBooking", b =>
                {
                    b.Property<int>("AdditionalServicesId")
                        .HasColumnType("int");

                    b.Property<int>("BookingsId")
                        .HasColumnType("int");

                    b.HasKey("AdditionalServicesId", "BookingsId");

                    b.HasIndex("BookingsId");

                    b.ToTable("AdditionalServicesBooking");
                });

            modelBuilder.Entity("AmenitiesRoom", b =>
                {
                    b.Property<int>("AmenitiesId")
                        .HasColumnType("int");

                    b.Property<int>("RoomsId")
                        .HasColumnType("int");

                    b.HasKey("AmenitiesId", "RoomsId");

                    b.HasIndex("RoomsId");

                    b.ToTable("AmenitiesRoom");
                });

            modelBuilder.Entity("TestLab.DataAccess.DbModels.AdditionalServices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("AdditionalServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "One-way transfer to airport",
                            Name = "Airport Shuttle",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Same-day wash and fold",
                            Name = "Laundry Service",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Full continental breakfast delivered",
                            Name = "Breakfast in Bed",
                            Price = 25.00m
                        });
                });

            modelBuilder.Entity("TestLab.DataAccess.DbModels.Amenities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Available in all rooms",
                            Name = "High-Speed Wi-Fi"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fully stocked with snacks and drinks",
                            Name = "Mini Bar"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Includes Netflix and local channels",
                            Name = "Smart TV"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Premium espresso machine",
                            Name = "Coffee Machine"
                        });
                });

            modelBuilder.Entity("TestLab.DataAccess.DbModels.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TestLab.DataAccess.DbModels.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusPoints")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TestLab.DataAccess.DbModels.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1,
                            Category = 0,
                            Description = "Standard Single Room",
                            ImageUrl = "room_standard_1.jpg",
                            PricePerNight = 85.00m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            Category = 1,
                            Description = "Deluxe Double Room",
                            ImageUrl = "room_deluxe_2.jpg",
                            PricePerNight = 150.00m
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            Category = 2,
                            Description = "Presidential Suite",
                            ImageUrl = "room_suite_3.jpg",
                            PricePerNight = 500.00m
                        });
                });

            modelBuilder.Entity("AdditionalServicesBooking", b =>
                {
                    b.HasOne("TestLab.DataAccess.DbModels.AdditionalServices", null)
                        .WithMany()
                        .HasForeignKey("AdditionalServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestLab.DataAccess.DbModels.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AmenitiesRoom", b =>
                {
                    b.HasOne("TestLab.DataAccess.DbModels.Amenities", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestLab.DataAccess.DbModels.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestLab.DataAccess.DbModels.Booking", b =>
                {
                    b.HasOne("TestLab.DataAccess.DbModels.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestLab.DataAccess.DbModels.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TestLab.DataAccess.DbModels.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TestLab.DataAccess.DbModels.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
